from enum import Enum

class Type(Enum):
    DATE = "DATE"
    NUMBER = "NUMBER"
    TEXT = "TEXT"
    MEASURER = "MEASURER"
    MEASURED = "MEASURED"
    QUESTIONS = "QUESTIONS"
    HEADER = "HEADER"
    CONTENT = "CONTENT"
    MEASURE = "MEASURE"
    SUBHEADER = "SUBHEADER"
